<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>

    <SupportedOSPlatformVersion>18.0</SupportedOSPlatformVersion>

    <ApplicationId>com.community.sts2launcher</ApplicationId>
    <ApplicationTitle>StS2 Launcher</ApplicationTitle>
    <ApplicationVersion>3</ApplicationVersion>
    <ApplicationDisplayVersion>0.0.3</ApplicationDisplayVersion>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
